# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_locator.ui'
#
# Created: Wed Jul 02 15:07:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(474, 359)
        self.toolBox = QtGui.QToolBox(Dialog)
        self.toolBox.setGeometry(QtCore.QRect(10, 20, 451, 321))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setFrameShape(QtGui.QFrame.Panel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Raised)
        self.toolBox.setLineWidth(2)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 447, 255))
        self.page.setAutoFillBackground(True)
        self.page.setObjectName(_fromUtf8("page"))
        self.cboStreet = QtGui.QComboBox(self.page)
        self.cboStreet.setGeometry(QtCore.QRect(150, 10, 241, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cboStreet.setFont(font)
        self.cboStreet.setEditable(True)
        self.cboStreet.setModelColumn(0)
        self.cboStreet.setObjectName(_fromUtf8("cboStreet"))
        self.label = QtGui.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.cboPortal = QtGui.QComboBox(self.page)
        self.cboPortal.setGeometry(QtCore.QRect(150, 40, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cboPortal.setFont(font)
        self.cboPortal.setEditable(True)
        self.cboPortal.setObjectName(_fromUtf8("cboPortal"))
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btnClose = QtGui.QPushButton(self.page)
        self.btnClose.setGeometry(QtCore.QRect(330, 130, 101, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnClose.setFont(font)
        self.btnClose.setLocale(QtCore.QLocale(QtCore.QLocale.Catalan, QtCore.QLocale.Spain))
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.btnSearch = QtGui.QPushButton(self.page)
        self.btnSearch.setGeometry(QtCore.QRect(220, 130, 101, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnSearch.setFont(font)
        self.btnSearch.setLocale(QtCore.QLocale(QtCore.QLocale.Catalan, QtCore.QLocale.Spain))
        self.btnSearch.setObjectName(_fromUtf8("btnSearch"))
        self.btnSearchStreet = QtGui.QPushButton(self.page)
        self.btnSearchStreet.setGeometry(QtCore.QRect(110, 130, 101, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnSearchStreet.setFont(font)
        self.btnSearchStreet.setLocale(QtCore.QLocale(QtCore.QLocale.Catalan, QtCore.QLocale.Spain))
        self.btnSearchStreet.setObjectName(_fromUtf8("btnSearchStreet"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 447, 255))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cboStreetLayer = QtGui.QComboBox(self.page_2)
        self.cboStreetLayer.setGeometry(QtCore.QRect(150, 10, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cboStreetLayer.setFont(font)
        self.cboStreetLayer.setObjectName(_fromUtf8("cboStreetLayer"))
        self.cboStreetCode = QtGui.QComboBox(self.page_2)
        self.cboStreetCode.setGeometry(QtCore.QRect(150, 40, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cboStreetCode.setFont(font)
        self.cboStreetCode.setObjectName(_fromUtf8("cboStreetCode"))
        self.cboStreetName = QtGui.QComboBox(self.page_2)
        self.cboStreetName.setGeometry(QtCore.QRect(150, 70, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cboStreetName.setFont(font)
        self.cboStreetName.setObjectName(_fromUtf8("cboStreetName"))
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cboPortalLayer = QtGui.QComboBox(self.page_2)
        self.cboPortalLayer.setGeometry(QtCore.QRect(150, 110, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cboPortalLayer.setFont(font)
        self.cboPortalLayer.setObjectName(_fromUtf8("cboPortalLayer"))
        self.cboPortalCode = QtGui.QComboBox(self.page_2)
        self.cboPortalCode.setGeometry(QtCore.QRect(150, 140, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cboPortalCode.setFont(font)
        self.cboPortalCode.setObjectName(_fromUtf8("cboPortalCode"))
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(20, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cboPortalNumber = QtGui.QComboBox(self.page_2)
        self.cboPortalNumber.setGeometry(QtCore.QRect(150, 170, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cboPortalNumber.setFont(font)
        self.cboPortalNumber.setObjectName(_fromUtf8("cboPortalNumber"))
        self.btnSave = QtGui.QPushButton(self.page_2)
        self.btnSave.setGeometry(QtCore.QRect(350, 200, 71, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnSave.setFont(font)
        self.btnSave.setLocale(QtCore.QLocale(QtCore.QLocale.Catalan, QtCore.QLocale.Spain))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(20, 210, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.cboScaleZoom = QtGui.QComboBox(self.page_2)
        self.cboScaleZoom.setGeometry(QtCore.QRect(150, 210, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cboScaleZoom.setFont(font)
        self.cboScaleZoom.setEditable(False)
        self.cboScaleZoom.setObjectName(_fromUtf8("cboScaleZoom"))
        self.label_10 = QtGui.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(140, 210, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Seleccionar carrer:", None))
        self.label_3.setText(_translate("Dialog", "Seleccionar portal:", None))
        self.btnClose.setText(_translate("Dialog", "Sortir", None))
        self.btnSearch.setText(_translate("Dialog", "Cercar Portal", None))
        self.btnSearchStreet.setText(_translate("Dialog", "Cercar Carrer", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Carrerer", None))
        self.label_2.setText(_translate("Dialog", "Capa carrers:", None))
        self.label_4.setText(_translate("Dialog", "Camp codi carrer:", None))
        self.label_5.setText(_translate("Dialog", "Camp nom carrer:", None))
        self.label_6.setText(_translate("Dialog", "Capa portals:", None))
        self.label_7.setText(_translate("Dialog", "Camp codi carrer:", None))
        self.label_8.setText(_translate("Dialog", "Camp número policia:", None))
        self.btnSave.setText(_translate("Dialog", "Desar", None))
        self.label_9.setText(_translate("Dialog", "Escala del zoom :", None))
        self.label_10.setText(_translate("Dialog", "1:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Dialog", "Configuració", None))

